#!/usr/bin/env bash

PYTHON="python3.10"

# Fail if anything fails
set -e

script_dir=$(dirname "$0")
venv_dir="$script_dir/env"

#Activate virtual environment
if [[ -z "$VIRTUAL_ENV" ]]; then
    if ! [[ -d "$venv_dir" ]]; then
        echo "Initializing virtual env in $venv_dir"
        "$PYTHON" -m venv "$venv_dir"
        source "$venv_dir/bin/activate"
        trap deactivate EXIT
        echo "Loading requirements"
        pip install -r "$script_dir/requirements.txt"
    else
        source "$venv_dir/bin/activate"
        trap deactivate EXIT
    fi
fi

# Run
python -m circuits "$@"
exit $?
